### ISSUE TITLE
is there any support to writing to disk?

### ISSUE THREAD

**Issue by nikita-skobov** [salmans/codd#44]
ie: can I write the in-memory database to disk if it grows too much, and can it later initialize itself from the data on the disk the next time it starts up?

**Comment by salmans** [comment]
@nikita-skobov sorry I somehow missed this. No, the library currently doesn't support that but it should be fairly straightforward to serialize/deserialize the database to a file the way that you suggested, if their tuple types implement `serde` traits. Working with instances directly from a file is more challenging and probably not one of the main goals of this project.

**Comment by nikita-skobov** [comment]
ok thanks for the reply
